export interface SubmoduleConfig {
  id: string;
  label: string;
  description?: string;
  badge?: string;
}

export interface ModuleConfig {
  id: string;
  code: string;
  label: string;
  route: string;
  iconName: string;
  description: string;
  submodules: SubmoduleConfig[];
}

export const MODULE_REGISTRY: ModuleConfig[] = [
  {
    id: 'dashboard',
    code: '01',
    label: 'Dashboard',
    route: '/',
    iconName: 'LayoutDashboard',
    description: 'Executive command center, role dashboards, and high-level institutional health',
    submodules: [
      { id: 'overview', label: 'Overview' },
      { id: 'operations', label: "Today's Operations" },
      { id: 'alerts', label: 'Alerts & Attention' },
      { id: 'upcoming', label: 'Upcoming' },
      { id: 'tasks', label: 'My Tasks' },
      { id: 'quick-actions', label: 'Quick Actions' },
      { id: 'role-dashboard', label: 'Role Dashboard' },
    ],
  },
  {
    id: 'admissions',
    code: '02',
    label: 'Admissions',
    route: '/admissions',
    iconName: 'UserSquare',
    description: 'Campaigns, applicant intake queue, entrance assessments, and student enrollment',
    submodules: [
      { id: 'dashboard', label: 'Admission Dashboard' },
      { id: 'enquiries', label: 'Enquiries' },
      { id: 'leads', label: 'Leads & Follow-ups' },
      { id: 'applications', label: 'Applications' },
      { id: 'forms', label: 'Admission Forms' },
      { id: 'documents', label: 'Applicant Documents' },
      { id: 'verification', label: 'Verification' },
      { id: 'interviews', label: 'Interviews & Assessments' },
      { id: 'selection', label: 'Selection & Approval' },
      { id: 'processing', label: 'Admission Processing' },
      { id: 'enrollment', label: 'Enrollment' },
      { id: 'fees', label: 'Admission Fees' },
      { id: 'communication', label: 'Admission Communication' },
      { id: 'campaigns', label: 'Admission Campaigns' },
      { id: 'reports', label: 'Admission Reports' },
      { id: 'settings', label: 'Admission Settings' },
    ],
  },
  {
    id: 'students',
    code: '03',
    label: 'Students',
    route: '/students',
    iconName: 'Users',
    description: 'Student 360° directory, guardian linkages, section allocations, and history',
    submodules: [
      { id: 'dashboard', label: 'Student Dashboard' },
      { id: 'all-students', label: 'All Students' },
      { id: 'profiles', label: 'Student Profiles' },
      { id: 'guardians', label: 'Parent & Guardian Records' },
      { id: 'class-section', label: 'Class & Section' },
      { id: 'id-cards', label: 'Student ID & Identity' },
      { id: 'status', label: 'Student Status' },
      { id: 'promotion', label: 'Promotion' },
      { id: 'transfer', label: 'Transfer' },
      { id: 'withdrawal', label: 'Withdrawal' },
      { id: 'readmission', label: 'Re-admission' },
      { id: 'history', label: 'Student History' },
      { id: 'bulk-operations', label: 'Bulk Student Operations' },
      { id: 'import-export', label: 'Import & Export' },
      { id: 'duplicates', label: 'Duplicate Management' },
      { id: 'search', label: 'Student Search' },
      { id: 'requests', label: 'Student Requests' },
      { id: 'settings', label: 'Student Settings' },
    ],
  },
  {
    id: 'academics',
    code: '04',
    label: 'Academics',
    route: '/academics',
    iconName: 'GraduationCap',
    description: 'Curriculum structure, subject allocations, academic sessions, and syllabus tracking',
    submodules: [
      { id: 'dashboard', label: 'Academic Dashboard' },
      { id: 'sessions', label: 'Academic Sessions' },
      { id: 'classes', label: 'Classes' },
      { id: 'sections', label: 'Sections' },
      { id: 'streams', label: 'Streams' },
      { id: 'departments', label: 'Departments' },
      { id: 'subjects', label: 'Subjects' },
      { id: 'subject-groups', label: 'Subject Groups' },
      { id: 'class-subject-mapping', label: 'Class-Subject Mapping' },
      { id: 'student-subject-mapping', label: 'Student-Subject Mapping' },
      { id: 'teacher-subject-mapping', label: 'Teacher-Subject Mapping' },
      { id: 'houses', label: 'Houses' },
      { id: 'calendar', label: 'Academic Calendar' },
      { id: 'working-days', label: 'Working Days' },
      { id: 'policies', label: 'Academic Policies' },
      { id: 'settings', label: 'Academic Settings' },
    ],
  },
  {
    id: 'timetable',
    code: '05',
    label: 'Timetable',
    route: '/timetable',
    iconName: 'Calendar',
    description: 'Period schedules, teacher workload balancing, room booking, and auto-substitutions',
    submodules: [
      { id: 'dashboard', label: 'Timetable Dashboard' },
      { id: 'master-timetable', label: 'Master Timetable' },
      { id: 'class-timetable', label: 'Class Timetable' },
      { id: 'teacher-timetable', label: 'Teacher Timetable' },
      { id: 'room-timetable', label: 'Room Timetable' },
      { id: 'period-structure', label: 'Period Structure' },
      { id: 'subject-scheduling', label: 'Subject Scheduling' },
      { id: 'teacher-workload', label: 'Teacher Workload' },
      { id: 'free-periods', label: 'Free Periods' },
      { id: 'substitutions', label: 'Substitution' },
      { id: 'conflicts', label: 'Timetable Conflicts' },
      { id: 'room-conflicts', label: 'Room Conflicts' },
      { id: 'temporary-changes', label: 'Temporary Changes' },
      { id: 'publishing', label: 'Timetable Publishing' },
      { id: 'reports', label: 'Timetable Reports' },
      { id: 'settings', label: 'Timetable Settings' },
    ],
  },
  {
    id: 'attendance',
    code: '06',
    label: 'Attendance',
    route: '/attendance',
    iconName: 'CalendarCheck',
    description: 'Biometric RFID/face sync, period attendance, employee shifts, and leave approvals',
    submodules: [
      { id: 'dashboard', label: 'Attendance Dashboard' },
      { id: 'todays-attendance', label: "Today's Attendance" },
      { id: 'class-attendance', label: 'Class Attendance' },
      { id: 'period-attendance', label: 'Period Attendance' },
      { id: 'student-attendance', label: 'Student Attendance' },
      { id: 'corrections', label: 'Attendance Corrections' },
      { id: 'leave-management', label: 'Leave Management' },
      { id: 'holiday-management', label: 'Holiday Management' },
      { id: 'late-early', label: 'Late & Early Records' },
      { id: 'summary', label: 'Attendance Summary' },
      { id: 'low-attendance', label: 'Low Attendance' },
      { id: 'alerts', label: 'Attendance Alerts' },
      { id: 'reports', label: 'Attendance Reports' },
      { id: 'settings', label: 'Attendance Settings' },
    ],
  },
  {
    id: 'teachers',
    code: '07',
    label: 'Teachers',
    route: '/teachers',
    iconName: 'Users',
    description: 'Faculty directory, employee 360° dossiers, qualifications, workload, and biometric logs',
    submodules: [
      { id: 'all-teachers', label: 'All Faculty & Teachers' },
      { id: 'workload', label: 'Teaching Workload' },
      { id: 'allocations', label: 'Class Allocations' },
      { id: 'onboarding', label: 'Faculty Onboarding' },
      { id: 'leaves', label: 'Faculty Leaves & Attendance' },
    ],
  },
  {
    id: 'learning',
    code: '08',
    label: 'Teaching',
    route: '/learning',
    iconName: 'BookOpenCheck',
    description: 'Lesson planning, curriculum frameworks, syllabus progress, and teaching diaries',
    submodules: [
      { id: 'dashboard', label: 'Teaching Dashboard' },
      { id: 'my-classes', label: 'My Classes' },
      { id: 'my-subjects', label: 'My Subjects' },
      { id: 'lesson-planning', label: 'Lesson Planning' },
      { id: 'teaching-plans', label: 'Teaching Plans' },
      { id: 'syllabus-curriculum', label: 'Syllabus & Curriculum' },
      { id: 'topics-chapters', label: 'Topics & Chapters' },
      { id: 'lesson-notes', label: 'Lesson Notes' },
      { id: 'teaching-diary', label: 'Teaching Diary' },
      { id: 'class-activities', label: 'Class Activities' },
      { id: 'learning-objectives', label: 'Learning Objectives' },
      { id: 'syllabus-progress', label: 'Syllabus Progress' },
      { id: 'class-progress', label: 'Class Progress' },
      { id: 'academic-performance', label: 'Academic Performance' },
      { id: 'teacher-planner', label: 'Teacher Planner' },
      { id: 'settings', label: 'Teaching Settings' },
    ],
  },
  {
    id: 'homework',
    code: '08',
    label: 'Homework',
    route: '/homework',
    iconName: 'BookMarked',
    description: 'Homework assignments, worksheets, projects, evaluation, and submission tracking',
    submodules: [
      { id: 'dashboard', label: 'Homework Dashboard' },
      { id: 'homework-list', label: 'Homework' },
      { id: 'assignments', label: 'Assignments' },
      { id: 'worksheets', label: 'Worksheets' },
      { id: 'projects', label: 'Projects' },
      { id: 'question-sets', label: 'Question Sets' },
      { id: 'distribution', label: 'Assignment Distribution' },
      { id: 'submissions', label: 'Student Submissions' },
      { id: 'review', label: 'Submission Review' },
      { id: 'evaluation', label: 'Evaluation & Marks' },
      { id: 'feedback', label: 'Teacher Feedback' },
      { id: 'resubmissions', label: 'Resubmissions' },
      { id: 'late-submissions', label: 'Late Submissions' },
      { id: 'completion-tracking', label: 'Completion Tracking' },
      { id: 'reports', label: 'Homework Reports' },
      { id: 'settings', label: 'Homework Settings' },
    ],
  },
  {
    id: 'examination',
    code: '09',
    label: 'Examinations',
    route: '/examinations',
    iconName: 'ClipboardList',
    description: 'Question bank generation, hall tickets, seating plans, evaluation, and report cards',
    submodules: [
      { id: 'dashboard', label: 'Examination Dashboard' },
      { id: 'exam-management', label: 'Exam Management' },
      { id: 'test-management', label: 'Test Management' },
      { id: 'assessment-types', label: 'Assessment Types' },
      { id: 'schedule', label: 'Exam Schedule' },
      { id: 'subject-paper-setup', label: 'Subject & Paper Setup' },
      { id: 'student-assignment', label: 'Student Exam Assignment' },
      { id: 'marks-entry', label: 'Marks Entry' },
      { id: 'marks-verification', label: 'Marks Verification' },
      { id: 'grades', label: 'Grades' },
      { id: 'remarks', label: 'Remarks' },
      { id: 'result-calculation', label: 'Result Calculation' },
      { id: 'result-processing', label: 'Result Processing' },
      { id: 'result-publishing', label: 'Result Publishing' },
      { id: 'report-cards', label: 'Report Cards' },
      { id: 'rank-position', label: 'Rank & Position' },
      { id: 'reports', label: 'Result Reports' },
      { id: 'settings', label: 'Examination Settings' },
    ],
  },
  {
    id: 'resources',
    code: '10',
    label: 'Learning Resources',
    route: '/resources',
    iconName: 'FolderGit2',
    description: 'Educational content management, study materials, PDFs, videos, and e-books',
    submodules: [
      { id: 'dashboard', label: 'Learning Dashboard' },
      { id: 'notes', label: 'Notes' },
      { id: 'study-materials', label: 'Study Materials' },
      { id: 'pdfs-documents', label: 'PDFs & Documents' },
      { id: 'videos', label: 'Videos' },
      { id: 'ebooks', label: 'E-books' },
      { id: 'external-links', label: 'External Links' },
      { id: 'subject-resources', label: 'Subject Resources' },
      { id: 'chapter-resources', label: 'Chapter Resources' },
      { id: 'teacher-resources', label: 'Teacher Resources' },
      { id: 'shared-resources', label: 'Shared Resources' },
      { id: 'collections', label: 'Learning Collections' },
      { id: 'access', label: 'Resource Access' },
      { id: 'analytics', label: 'Resource Analytics' },
      { id: 'settings', label: 'Learning Settings' },
    ],
  },
  {
    id: 'lms',
    code: '11',
    label: 'Online Classes',
    route: '/lms',
    iconName: 'Laptop',
    description: 'Virtual learning management, live classes, meeting schedules, and recordings',
    submodules: [
      { id: 'dashboard', label: 'Online Class Dashboard' },
      { id: 'schedule', label: 'Class Schedule' },
      { id: 'create-class', label: 'Create Online Class' },
      { id: 'live-classes', label: 'Live Classes' },
      { id: 'meeting-management', label: 'Meeting Management' },
      { id: 'attendance', label: 'Online Attendance' },
      { id: 'class-materials', label: 'Class Materials' },
      { id: 'content-sharing', label: 'Screen/Content Sharing' },
      { id: 'recordings', label: 'Recordings' },
      { id: 'recorded-classes', label: 'Recorded Classes' },
      { id: 'history', label: 'Online Class History' },
      { id: 'reports', label: 'Online Class Reports' },
      { id: 'settings', label: 'Online Class Settings' },
    ],
  },
  {
    id: 'portal',
    code: '12',
    label: 'Parent & Student Portal',
    route: '/portal',
    iconName: 'GraduationCap',
    description: 'Dedicated student & guardian portal for grades, attendance, and timetable',
    submodules: [
      { id: 'home', label: 'Home' },
      { id: 'academics', label: 'Academics' },
      { id: 'calendar', label: 'Calendar' },
      { id: 'communication', label: 'Communication' },
      { id: 'profile', label: 'Profile & Services' },
    ],
  },
  {
    id: 'settings',
    code: '13',
    label: 'Settings',
    route: '/settings',
    iconName: 'Settings',
    description: 'Core school-wide configuration, campuses, academic sessions, branding, and policies',
    submodules: [
      { id: 'dashboard', label: 'School Dashboard' },
      { id: 'school-profile', label: 'School Profile' },
      { id: 'campuses-branches', label: 'Campuses & Branches' },
      { id: 'sessions', label: 'Academic Sessions' },
      { id: 'calendar', label: 'School Calendar' },
      { id: 'departments', label: 'Departments' },
      { id: 'classes-sections', label: 'Classes & Sections' },
      { id: 'houses', label: 'Houses' },
      { id: 'branding', label: 'School Branding' },
      { id: 'policies', label: 'School Policies' },
      { id: 'preferences', label: 'General Preferences' },
      { id: 'configuration', label: 'School Configuration' },
      { id: 'numbering-codes', label: 'Numbering & Codes' },
      { id: 'import-export', label: 'Data Import/Export' },
      { id: 'settings', label: 'School Settings' },
    ],
  },
  {
    id: 'privacy',
    code: '14',
    label: 'Privacy & DPDP',
    route: '/privacy',
    iconName: 'ShieldCheck',
    description: 'Digital Personal Data Protection Act 2023 compliance, parental consent, DSR rights, and grievance redressal',
    submodules: [
      { id: 'overview', label: 'DPDP Overview' },
      { id: 'parental-consent', label: 'Parental Consent (Sec 9)' },
      { id: 'consent-studio', label: 'Consent Studio (Sec 6)' },
      { id: 'data-rights', label: 'Data Rights Hub (Sec 11-14)' },
      { id: 'grievance-registry', label: 'Grievance Redressal (Sec 13)' },
      { id: 'privacy-notice', label: 'Privacy Notice (Sec 5)' },
      { id: 'retention-matrix', label: 'Retention Schedule' },
      { id: 'breach-response', label: 'Breach Response' },
    ],
  },
];
