import {
  ConsentPurposeDefinition,
  RetentionPolicyItem,
  ThirdPartyProcessorItem,
  PrivacyGrievanceTicket,
  DataSubjectRequest,
  VerifiableParentalConsent,
  DataBreachIncident,
  PrivacyMetricsOverview,
} from '@vidyafloww/types';

export const DPDP_NOTICE_VERSION = '2026.1-DPDP';
export const DPDP_NOTICE_EFFECTIVE_DATE = '01 January 2026';

export const DPDP_OFFICER_CONFIG = {
  name: 'Adv. Ananya Deshmukh',
  title: 'Data Protection Officer (DPO) & Grievance Redressal Officer',
  organization: 'VidyaFloww Institutional Trust & Network',
  address: 'Plot 14, Institutional Area, Sector 62, New Delhi 110092, India',
  email: 'dpo@vidyafloww.com',
  phone: '+91 11 4987 2300',
  jurisdiction: 'India (Designated under DPDP Act, 2023 & DPDP Rules, 2025)',
  statutorySlaDays: 90,
  institutionalTargetDays: 7,
  dpbiPortalUrl: 'https://dpb.gov.in',
};

export const DPDP_CONSENT_PURPOSES: ConsentPurposeDefinition[] = [
  {
    id: 'core_academics',
    name: 'Core Education & Academic Records',
    nameHi: 'मूल शिक्षा एवं अकादमिक रिकॉर्ड',
    description: 'Enrolment, class rosters, attendance registers, CBSE/State board examination marks, and transfer certificate issuance.',
    descriptionHi: 'नामांकन, कक्षा रोस्टर, उपस्थिति रजिस्टर, सीबीएसई/राज्य बोर्ड परीक्षा अंक और स्थानांतरण प्रमाण पत्र जारी करना।',
    dataCategories: ['Legal Name', 'Date of Birth', 'Gender', 'Roll No', 'Class & Section', 'Guardian Contacts', 'Academic Transcripts'],
    isEssential: true,
    lawfulBasis: 'statutory_obligation',
    retentionPeriod: 'Enrolment Duration + 5 Years (CBSE/NEP Mandate)',
    thirdParties: ['AWS Sovereign Mumbai (DB Storage)', 'CBSE Examination Server'],
  },
  {
    id: 'emergency_medical',
    name: 'Student Emergency Healthcare & Allergies',
    nameHi: 'छात्र आपातकालीन स्वास्थ्य सेवा एवं एलर्जी',
    description: 'Blood group, chronic condition alerts, physician contacts, and infirmary first-aid records for immediate medical safety.',
    descriptionHi: 'तत्काल चिकित्सा सुरक्षा के लिए रक्त समूह, पुरानी बीमारी अलर्ट, चिकित्सक संपर्क और प्राथमिक चिकित्सा रिकॉर्ड।',
    dataCategories: ['Blood Group', 'Medical Notes', 'Emergency Doctor Contact', 'Allergy Flags'],
    isEssential: true,
    lawfulBasis: 'legitimate_use',
    retentionPeriod: 'Enrolment Duration (Purged upon Transfer/Graduation)',
    thirdParties: ['Campus Health Clinic System'],
  },
  {
    id: 'transport_telemetry',
    name: 'Live GPS Fleet Tracking & Stop Telemetry',
    nameHi: 'लाइव जीपीएस बस ट्रैकिंग और स्टॉप टेलीमेट्री',
    description: 'Live bus coordinate tracking, estimated arrival broadcasts, and driver quick-calling for student transit safety.',
    descriptionHi: 'छात्र परिवहन सुरक्षा के लिए लाइव बस समन्वय ट्रैकिंग, अनुमानित आगमन अलर्ट और ड्राइवर त्वरित-कॉल।',
    dataCategories: ['Designated Bus Route', 'Pickup/Drop Bus Stop', 'GPS Telemetry Coordinates'],
    isEssential: false,
    lawfulBasis: 'consent',
    retentionPeriod: '90 Days Rolling Window (Telemetry Purged)',
    thirdParties: ['Indian Fleet Telematics (AIS-140 GPS Server)'],
  },
  {
    id: 'biometric_access',
    name: 'Turnstile Biometric & Smart Access Control',
    nameHi: 'टर्नस्टाइल बायोमेट्रिक और स्मार्ट एक्सेस कंट्रोल',
    description: 'Automated campus gate entry/exit logging via contactless turnstiles and RFID smart badges.',
    descriptionHi: 'कॉन्टैक्टलेस टर्नस्टाइल और आरएफआईडी स्मार्ट बैज के माध्यम से स्वचालित कैंपस गेट प्रवेश/निकास लॉगिंग।',
    dataCategories: ['Gate Access Timestamp', 'Turnstile Node ID', 'Punch Status'],
    isEssential: false,
    lawfulBasis: 'consent',
    retentionPeriod: '180 Days (Auto-purged from edge controllers)',
    thirdParties: ['Campus Local Turnstile Hardware Controller'],
  },
  {
    id: 'communication_broadcasts',
    name: 'Institutional Alerts (WhatsApp & SMS Circulars)',
    nameHi: 'संस्थागत अलर्ट (व्हाट्सएप और एसएमएस परिपत्र)',
    description: 'Official announcements, emergency holiday alerts, fee dues reminders, and academic circulars.',
    descriptionHi: 'आधिकारिक घोषणाएं, आपातकालीन अवकाश अलर्ट, शुल्क देय अनुस्मारक और शैक्षणिक परिपत्र।',
    dataCategories: ['Primary Mobile Number', 'Parent Email Address'],
    isEssential: false,
    lawfulBasis: 'consent',
    retentionPeriod: 'Duration of Consent (Instant revocation on opt-out)',
    thirdParties: ['MSG91 SMS Gateway (India)', 'Gupshup WhatsApp Enterprise (India)'],
  },
  {
    id: 'scholarships_aid',
    name: 'Merit & Financial Aid Eligibility Evaluation',
    nameHi: 'योग्यता और वित्तीय सहायता पात्रता मूल्यांकन',
    description: 'Income category certificates and economic criteria for tuition waivers under RTE and merit schemes.',
    descriptionHi: 'आरटीई और मेरिट योजनाओं के तहत ट्यूशन छूट के लिए आय श्रेणी प्रमाण पत्र और आर्थिक मानदंड।',
    dataCategories: ['Income Slab', 'Quota Category', 'Bank Account / IFSC (for disbursements)'],
    isEssential: false,
    lawfulBasis: 'consent',
    retentionPeriod: 'Disbursement Fiscal Year + 3 Years for Audit',
    thirdParties: ['Institutional Treasury & Bank Gateway'],
  },
];

export const RETENTION_POLICY_MATRIX: RetentionPolicyItem[] = [
  {
    id: 'RET-01',
    dataCategory: 'Active Student Academic & Enrolment Records',
    applicableDataFields: ['Student Name', 'DOB', 'Roll No', 'Class', 'Marks', 'CBSE Registration'],
    processingPurpose: 'Academic Instruction, Grading, and Statutory CBSE Certification',
    statutoryBasis: 'Right to Education Act / CBSE Affiliation Bye-Laws 2018',
    retentionPeriod: 'Enrolment Duration + 5 Years post-graduation',
    deletionMethod: 'Archival Vault',
    cbseStatutoryPreservation: true,
  },
  {
    id: 'RET-02',
    dataCategory: 'Non-Admitted Applicant Records',
    applicableDataFields: ['Applicant Name', 'Parent Contact', 'Interview Scores', 'Previous School Docs'],
    processingPurpose: 'Admission Funnel Evaluation',
    statutoryBasis: 'DPDP Act, 2023 Purpose Limitation (Sec. 6)',
    retentionPeriod: '365 Days from Admission Cycle Close',
    deletionMethod: 'Cryptographic Shredding',
    cbseStatutoryPreservation: false,
  },
  {
    id: 'RET-03',
    dataCategory: 'Campus Gate Biometric & Turnstile Logs',
    applicableDataFields: ['Gate Number', 'Punch Timestamp', 'Turnstile Hardware ID'],
    processingPurpose: 'Campus Physical Security & Entry Verification',
    statutoryBasis: 'DPDP Act, 2023 Reasonable Security Safeguards (Sec. 8)',
    retentionPeriod: '180 Days (Automated Rolling Purge)',
    deletionMethod: 'Hard Deletion',
    cbseStatutoryPreservation: false,
  },
  {
    id: 'RET-04',
    dataCategory: 'Fleet GPS Telemetry & Transit Coordinates',
    applicableDataFields: ['Bus Latitude/Longitude', 'Speed Telemetry', 'Stop Arrival Times'],
    processingPurpose: 'Live Student Transit Monitoring & Safety',
    statutoryBasis: 'Motor Vehicles Act / AIS-140 Guidelines',
    retentionPeriod: '90 Days',
    deletionMethod: 'Hard Deletion',
    cbseStatutoryPreservation: false,
  },
  {
    id: 'RET-05',
    dataCategory: 'Financial Invoices, Fee Receipts & Tax Ledgers',
    applicableDataFields: ['Fee Receipt No', 'Payer Name', 'GST Breakdown', 'Transaction Reference'],
    processingPurpose: 'Statutory Financial Audit & Tax Compliance',
    statutoryBasis: 'Income Tax Act, 1961 / GST Act 2017 (Sec. 36)',
    retentionPeriod: '8 Years from end of relevant assessment year',
    deletionMethod: 'Archival Vault',
    cbseStatutoryPreservation: true,
  },
  {
    id: 'RET-06',
    dataCategory: 'Consent Records & Data Subject Request Audit Trails',
    applicableDataFields: ['Principal ID', 'Consent Purpose', 'Timestamp', 'DSR Resolution Proof'],
    processingPurpose: 'Demonstration of Compliance & Accountability to DPBI',
    statutoryBasis: 'DPDP Rules, 2025 Audit & Accountability Standard',
    retentionPeriod: '5 Years post consent revocation / request completion',
    deletionMethod: 'Anonymisation',
    cbseStatutoryPreservation: false,
  },
];

export const THIRD_PARTY_PROCESSORS: ThirdPartyProcessorItem[] = [
  {
    id: 'PROC-01',
    serviceName: 'Amazon Web Services (AWS)',
    vendorName: 'Amazon Web Services India Private Limited',
    role: 'Cloud Infrastructure',
    personalDataTransferred: ['Encrypted PostgreSQL DB Backups', 'Encrypted Student Documents'],
    purpose: 'Sovereign cloud hosting and AES-256 storage',
    dataHostingLocation: 'Mumbai Region (ap-south-1), India',
    isCrossBorderTransfer: false,
    dpaSigned: true,
    encryptionStandard: 'AES-256 at Rest, TLS 1.3 in Transit',
  },
  {
    id: 'PROC-02',
    serviceName: 'MSG91 Enterprise SMS',
    vendorName: 'Walkover Technologies Private Limited',
    role: 'SMS Gateway',
    personalDataTransferred: ['Parent Mobile Number', 'Student Name (in Alert snippet)'],
    purpose: 'Dispatch of mandatory OTPs, attendance notices, and emergency alerts',
    dataHostingLocation: 'Noida / Bengaluru Data Centers, India',
    isCrossBorderTransfer: false,
    dpaSigned: true,
    encryptionStandard: 'HTTPS API / TLS 1.3 / DLT Registered Headers',
  },
  {
    id: 'PROC-03',
    serviceName: 'Gupshup WhatsApp Business Platform',
    vendorName: 'Gupshup Technology India Private Limited',
    role: 'WhatsApp Gateway',
    personalDataTransferred: ['Parent WhatsApp Number', 'Student First Name', 'Fee Receipt Link'],
    purpose: 'Dissemination of official circulars and digital fee receipts upon parent consent',
    dataHostingLocation: 'Mumbai Data Centers, India',
    isCrossBorderTransfer: false,
    dpaSigned: true,
    encryptionStandard: 'End-to-End WhatsApp Encryption + TLS 1.3 API',
  },
  {
    id: 'PROC-04',
    serviceName: 'Razorpay Payment Gateway',
    vendorName: 'Razorpay Software Private Limited',
    role: 'Payment Aggregator',
    personalDataTransferred: ['Payer Name', 'Email Address', 'Payment Amount', 'Invoice Number'],
    purpose: 'PCI-DSS Level 1 tokenized online fee collection (no card numbers stored by school)',
    dataHostingLocation: 'Bengaluru / Mumbai, India',
    isCrossBorderTransfer: false,
    dpaSigned: true,
    encryptionStandard: 'PCI-DSS Level 1 / AES-256 / SHA-256 Tokenization',
  },
];

export const INITIAL_VERIFIABLE_PARENTAL_CONSENTS: VerifiableParentalConsent[] = [
  {
    id: 'VPC-2026-001',
    studentId: 'STU-2026-001',
    studentName: 'Aarav Sharma',
    studentDob: '12-05-2010',
    isMinor: true,
    guardianName: 'Dr. Rajesh Sharma',
    guardianRelationship: 'Father',
    guardianPhone: '+91 98101 23456',
    guardianEmail: 'rajesh.sharma@example.com',
    verificationMethod: 'Aadhaar_OTP',
    verificationStatus: 'Verified',
    consentGrantedAt: '15 Jan 2026, 10:30 AM',
    tokenizedProofId: 'VPC-SIG-SHA256-8F9B2C4D',
    prohibitTrackingAffirmed: true,
    prohibitTargetedAdsAffirmed: true,
  },
  {
    id: 'VPC-2026-002',
    studentId: 'STU-2026-002',
    studentName: 'Diya Patel',
    studentDob: '28-09-2009',
    isMinor: true,
    guardianName: 'Meera Patel',
    guardianRelationship: 'Mother',
    guardianPhone: '+91 98202 34567',
    guardianEmail: 'meera.patel@example.com',
    verificationMethod: 'Digital_Sign',
    verificationStatus: 'Verified',
    consentGrantedAt: '18 Jan 2026, 02:15 PM',
    tokenizedProofId: 'VPC-SIG-SHA256-3A7E9F11',
    prohibitTrackingAffirmed: true,
    prohibitTargetedAdsAffirmed: true,
  },
  {
    id: 'VPC-2026-003',
    studentId: 'STU-2026-003',
    studentName: 'Rohan Verma',
    studentDob: '04-11-2011',
    isMinor: true,
    guardianName: 'Sunil Verma',
    guardianRelationship: 'Father',
    guardianPhone: '+91 98303 45678',
    guardianEmail: 'sunil.verma@example.com',
    verificationMethod: 'Physical_Dossier',
    verificationStatus: 'Verified',
    consentGrantedAt: '22 Jan 2026, 11:00 AM',
    tokenizedProofId: 'VPC-SIG-SHA256-5B2E8890',
    prohibitTrackingAffirmed: true,
    prohibitTargetedAdsAffirmed: true,
  },
  {
    id: 'VPC-2026-004',
    studentId: 'STU-2026-004',
    studentName: 'Ananya Gupta',
    studentDob: '19-03-2010',
    isMinor: true,
    guardianName: 'Arun Gupta',
    guardianRelationship: 'Father',
    guardianPhone: '+91 98404 56789',
    guardianEmail: 'arun.gupta@example.com',
    verificationMethod: 'Portal_Auth',
    verificationStatus: 'Pending Verification',
    consentGrantedAt: '28 Jan 2026, 09:40 AM',
    tokenizedProofId: 'VPC-SIG-SHA256-PENDING-441',
    prohibitTrackingAffirmed: true,
    prohibitTargetedAdsAffirmed: true,
  },
];

export const INITIAL_DATA_SUBJECT_REQUESTS: DataSubjectRequest[] = [
  {
    id: 'DSR-2026-041',
    requestNumber: 'DSR-REQ-9041',
    principalId: 'PAR-9021',
    principalName: 'Sunil Verma',
    principalRole: 'Parent',
    requesterContact: 'sunil.verma@example.com',
    rightType: 'access_summary',
    description: 'Requesting comprehensive downloadable electronic summary of all personal data held for ward Rohan Verma (Class 9-B).',
    status: 'Completed',
    submittedAt: '12 Sep 2026, 09:15 AM',
    slaDeadline: '12 Oct 2026 (30-day statutory SLA)',
    completedAt: '14 Sep 2026, 03:30 PM',
    assignedOfficer: 'Adv. Ananya Deshmukh (DPO)',
    resolutionNotes: 'Encrypted ZIP dossier archive generated and dispatched to verified parent email with SHA-256 checksum.',
    isStatutoryRetentionExempt: false,
  },
  {
    id: 'DSR-2026-042',
    requestNumber: 'DSR-REQ-9042',
    principalId: 'PAR-9044',
    principalName: 'Meera Patel',
    principalRole: 'Parent',
    requesterContact: 'meera.patel@example.com',
    rightType: 'updating',
    description: 'Update residential address and secondary emergency contact number due to house relocation.',
    targetFields: ['address', 'emergencyContact'],
    requestedChanges: {
      address: 'Flat 402, Lotus Heights, Indirapuram, Ghaziabad, UP 201014',
      emergencyContact: '+91 98111 99882',
    },
    status: 'Completed',
    submittedAt: '14 Sep 2026, 11:20 AM',
    slaDeadline: '14 Oct 2026',
    completedAt: '15 Sep 2026, 10:10 AM',
    assignedOfficer: 'Registrar / Front Office',
    resolutionNotes: 'Verified utility bill proof and synchronized with Central Student Dossier and Transport Route Matrix.',
    isStatutoryRetentionExempt: false,
  },
  {
    id: 'DSR-2026-043',
    requestNumber: 'DSR-REQ-9043',
    principalId: 'ALUM-2024-88',
    principalName: 'Vikas Malhotra (Former Student)',
    principalRole: 'Student',
    requesterContact: 'vikas.m@alumni.org',
    rightType: 'erasure',
    description: 'Requesting complete deletion of student portal login tokens, optional survey feedback, and bus route logs.',
    status: 'Processing',
    submittedAt: '20 Sep 2026, 02:40 PM',
    slaDeadline: '20 Oct 2026',
    assignedOfficer: 'Adv. Ananya Deshmukh (DPO)',
    resolutionNotes: 'Optional telemetry, marketing preferences, and session tokens queued for purge. CBSE permanent marksheet records preserved under statutory obligation.',
    isStatutoryRetentionExempt: true,
  },
  {
    id: 'DSR-2026-044',
    requestNumber: 'DSR-REQ-9044',
    principalId: 'TEA-401',
    principalName: 'Dr. Sarah Connor',
    principalRole: 'Teacher',
    requesterContact: 'sarah.c@vidyafloww.com',
    rightType: 'nomination',
    description: 'Nominate spouse (John Connor) as lawful representative to exercise Data Principal rights in event of medical incapacity.',
    nomineeDetails: {
      fullName: 'John Connor',
      relationship: 'Spouse',
      contactPhone: '+91 98765 43210',
      email: 'john.c@example.com',
    },
    status: 'Identity Verified',
    submittedAt: '24 Sep 2026, 04:00 PM',
    slaDeadline: '24 Oct 2026',
    assignedOfficer: 'HR Compliance Officer',
    resolutionNotes: 'Government ID verification verified. Awaiting final DPO digital endorsement.',
    isStatutoryRetentionExempt: false,
  },
];

export const INITIAL_PRIVACY_GRIEVANCES: PrivacyGrievanceTicket[] = [
  {
    id: 'GRIEV-2026-101',
    ticketNumber: 'GRV-DPDP-9101',
    complainantName: 'Kavita Sundaram',
    complainantRole: 'Parent',
    complainantEmail: 'kavita.s@example.com',
    complainantPhone: '+91 98200 11223',
    category: 'Biometric / Telemetry Tracking Concern',
    subject: 'Request clarity on turnstile biometric template storage and opt-out provision',
    description: 'Parent inquiring whether student biometric templates are stored locally or in cloud, and requesting RFID card alternative.',
    priority: 'Medium',
    lodgedDate: '18 Sep 2026, 11:30 AM',
    statutorySlaDeadline: '17 Dec 2026 (90-day DPDP limit)',
    internalSlaTarget: '25 Sep 2026 (7-day institutional SLA)',
    assignedGrievanceOfficer: 'Adv. Ananya Deshmukh (DPO)',
    status: 'Resolved',
    resolutionSummary: 'Detailed clarification sent confirming templates are stored locally on isolated controller with SHA-256 encryption. Passive RFID card issued as frictionless alternative.',
    resolvedAt: '21 Sep 2026, 04:15 PM',
    dpbiEscalationEligible: false,
  },
  {
    id: 'GRIEV-2026-102',
    ticketNumber: 'GRV-DPDP-9102',
    complainantName: 'Deepak Joshi',
    complainantRole: 'Parent',
    complainantEmail: 'deepak.j@example.com',
    complainantPhone: '+91 98111 22334',
    category: 'Consent Withdrawal Refusal',
    subject: 'Promotional WhatsApp circular received after opting out in portal settings',
    description: 'Opted out of non-academic broadcast notifications last week but received annual fete promotional message on WhatsApp.',
    priority: 'High',
    lodgedDate: '23 Sep 2026, 03:00 PM',
    statutorySlaDeadline: '22 Dec 2026',
    internalSlaTarget: '30 Sep 2026',
    assignedGrievanceOfficer: 'Adv. Ananya Deshmukh (DPO)',
    status: 'Under Investigation',
    resolutionSummary: 'Identified delay in third-party Gupshup webhook synchronization. Fixed synchronization pipeline and confirmed manual suppression on vendor side.',
    dpbiEscalationEligible: false,
  },
];

export const INITIAL_DATA_BREACH_LOGS: DataBreachIncident[] = [
  {
    id: 'INC-2026-001',
    incidentRef: 'INC-SEC-891',
    title: 'Simulated Network Perimeter Port Scan & Rapid Containment',
    severity: 'Low',
    categoriesAffected: ['Network Gateway Telemetry (Zero Personal Data Compromised)'],
    estimatedAffectedPrincipals: 0,
    detectedAt: '01 Sep 2026, 03:12 AM',
    containedAt: '01 Sep 2026, 03:15 AM',
    status: 'Remediated',
    boardNotificationRequired: false,
    boardNotificationStatus: 'Not Required',
    principalNotificationStatus: 'Not Required',
    containmentMeasures: 'Automated AWS WAF rule triggered; source IP blocked at edge with zero latency.',
    remediationPlan: 'WAF perimeter rate limit reduced from 200 req/min to 100 req/min for non-authenticated public endpoints.',
  },
];

export const INITIAL_PRIVACY_METRICS: PrivacyMetricsOverview = {
  totalPrincipalsProtected: 2451,
  activeConsentRecords: 2380,
  minorVpcComplianceRate: 98.4,
  openDSRRequests: 2,
  openGrievances: 1,
  statutoryRetentionCompliance: 100,
  sovereignDataResidency: '100% In-Region (India / Mumbai ap-south-1)',
  dpoDesignated: true,
};
