# Generated by Django 5.2.17 on 2026-09-26 14:22

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DataBreachIncidentRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "incident_ref",
                    models.CharField(db_index=True, max_length=32, unique=True),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("Critical", "Critical"),
                            ("High", "High"),
                            ("Medium", "Medium"),
                            ("Low", "Low"),
                        ],
                        default="Low",
                        max_length=16,
                    ),
                ),
                ("categories_affected", models.JSONField(default=list)),
                ("affected_principals_count", models.PositiveIntegerField(default=0)),
                (
                    "detected_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("contained_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Detected", "Detected"),
                            ("Triaged", "Triaged"),
                            ("Contained", "Contained"),
                            ("DPBI Notified", "DPBI Notified"),
                            ("Principals Notified", "Principals Notified"),
                            ("Remediated", "Remediated"),
                        ],
                        default="Detected",
                        max_length=32,
                    ),
                ),
                ("board_notification_required", models.BooleanField(default=False)),
                (
                    "board_notification_status",
                    models.CharField(default="Not Required", max_length=32),
                ),
                ("board_notified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "principal_notification_status",
                    models.CharField(default="Not Required", max_length=32),
                ),
                ("containment_measures", models.TextField(blank=True, default="")),
                ("remediation_plan", models.TextField(blank=True, default="")),
            ],
            options={
                "db_table": "dpdp_breach_incidents",
                "ordering": ["-detected_at"],
            },
        ),
        migrations.CreateModel(
            name="DataSubjectRequestRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "request_number",
                    models.CharField(db_index=True, max_length=32, unique=True),
                ),
                ("principal_id", models.CharField(db_index=True, max_length=64)),
                ("principal_name", models.CharField(max_length=255)),
                ("principal_role", models.CharField(default="Student", max_length=32)),
                ("requester_contact", models.CharField(max_length=255)),
                (
                    "right_type",
                    models.CharField(
                        choices=[
                            ("access_summary", "Right to Access Summary"),
                            ("correction", "Right to Correction"),
                            ("completion", "Right to Completion"),
                            ("updating", "Right to Updating"),
                            ("erasure", "Right to Erasure"),
                            ("nomination", "Right to Nominate"),
                        ],
                        max_length=32,
                    ),
                ),
                ("description", models.TextField()),
                ("target_fields", models.JSONField(blank=True, default=list)),
                ("requested_changes", models.JSONField(blank=True, default=dict)),
                ("nominee_details", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Submitted", "Submitted"),
                            ("Identity Verified", "Identity Verified"),
                            ("Under Review", "Under Review"),
                            ("Processing", "Processing"),
                            ("Completed", "Completed"),
                            ("Rejected", "Rejected"),
                        ],
                        default="Submitted",
                        max_length=32,
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("sla_deadline", models.DateTimeField()),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_officer",
                    models.CharField(default="Data Protection Officer", max_length=255),
                ),
                ("resolution_notes", models.TextField(blank=True, default="")),
                ("is_statutory_retention_exempt", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "dpdp_subject_requests",
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="PrivacyGrievanceRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "ticket_number",
                    models.CharField(db_index=True, max_length=32, unique=True),
                ),
                ("complainant_name", models.CharField(max_length=255)),
                ("complainant_role", models.CharField(default="Parent", max_length=32)),
                ("complainant_email", models.EmailField(max_length=254)),
                ("complainant_phone", models.CharField(max_length=32)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            (
                                "Consent Withdrawal Refusal",
                                "Consent Withdrawal Refusal",
                            ),
                            (
                                "Unauthorised Personal Data Processing",
                                "Unauthorised Personal Data Processing",
                            ),
                            (
                                "Data Inaccuracy & Correction Delay",
                                "Data Inaccuracy & Correction Delay",
                            ),
                            ("Erasure Request Default", "Erasure Request Default"),
                            ("Minor Data Safeguards", "Minor Data Safeguards"),
                            (
                                "Biometric / Telemetry Tracking Concern",
                                "Biometric / Telemetry Tracking Concern",
                            ),
                            ("Security / Breach Concern", "Security / Breach Concern"),
                        ],
                        max_length=64,
                    ),
                ),
                ("subject", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("Urgent", "Urgent"),
                            ("High", "High"),
                            ("Medium", "Medium"),
                            ("Low", "Low"),
                        ],
                        default="Medium",
                        max_length=16,
                    ),
                ),
                (
                    "lodged_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("statutory_sla_deadline", models.DateTimeField()),
                ("internal_sla_target", models.DateTimeField()),
                (
                    "assigned_officer",
                    models.CharField(
                        default="Adv. Ananya Deshmukh (DPO)", max_length=255
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Open", "Open"),
                            ("Under Investigation", "Under Investigation"),
                            ("Remediation in Progress", "Remediation in Progress"),
                            ("Resolved", "Resolved"),
                            ("Escalated to Board", "Escalated to Board"),
                        ],
                        default="Open",
                        max_length=32,
                    ),
                ),
                ("resolution_summary", models.TextField(blank=True, default="")),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("dpbi_escalation_eligible", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "dpdp_privacy_grievances",
                "ordering": ["-lodged_date"],
            },
        ),
        migrations.CreateModel(
            name="VerifiableParentalConsentRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("student_id", models.CharField(db_index=True, max_length=64)),
                ("student_name", models.CharField(max_length=255)),
                ("student_dob", models.CharField(max_length=32)),
                ("is_minor", models.BooleanField(default=True)),
                ("guardian_name", models.CharField(max_length=255)),
                (
                    "guardian_relationship",
                    models.CharField(
                        choices=[
                            ("Father", "Father"),
                            ("Mother", "Mother"),
                            ("Legal Guardian", "Legal Guardian"),
                        ],
                        max_length=32,
                    ),
                ),
                ("guardian_phone", models.CharField(max_length=32)),
                ("guardian_email", models.EmailField(max_length=254)),
                (
                    "verification_method",
                    models.CharField(
                        choices=[
                            ("Aadhaar_OTP", "Aadhaar OTP (UIDAI Sandbox)"),
                            ("Digital_Sign", "Digital Signature Token"),
                            ("Physical_Dossier", "Physical Signed Admission Dossier"),
                            ("Portal_Auth", "Authenticated Parent Portal Session"),
                        ],
                        default="Portal_Auth",
                        max_length=32,
                    ),
                ),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("Verified", "Verified"),
                            ("Pending Verification", "Pending Verification"),
                            ("Rejected", "Rejected"),
                        ],
                        default="Verified",
                        max_length=32,
                    ),
                ),
                (
                    "consent_granted_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("tokenized_proof_id", models.CharField(max_length=128, unique=True)),
                ("prohibit_tracking_affirmed", models.BooleanField(default=True)),
                ("prohibit_targeted_ads_affirmed", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "dpdp_parental_consents",
                "ordering": ["-consent_granted_at"],
            },
        ),
        migrations.CreateModel(
            name="ConsentAuditRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("principal_id", models.CharField(db_index=True, max_length=64)),
                ("principal_name", models.CharField(max_length=255)),
                (
                    "principal_role",
                    models.CharField(
                        choices=[
                            ("Student", "Student"),
                            ("Parent", "Parent"),
                            ("Teacher", "Teacher"),
                            ("Staff", "Staff"),
                        ],
                        default="Student",
                        max_length=32,
                    ),
                ),
                (
                    "purpose_id",
                    models.CharField(
                        choices=[
                            ("core_academics", "Core Academics & Enrolment"),
                            ("emergency_medical", "Emergency Medical Healthcare"),
                            ("transport_telemetry", "Live Transport & GPS Telemetry"),
                            ("biometric_access", "Turnstile Biometric & Smart Access"),
                            (
                                "communication_broadcasts",
                                "Communication Broadcasts & Alerts",
                            ),
                            ("scholarships_aid", "Scholarships & Financial Aid"),
                        ],
                        max_length=64,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("granted", "Granted"),
                            ("withdrawn", "Withdrawn"),
                            ("pending", "Pending"),
                            ("expired", "Expired"),
                        ],
                        default="granted",
                        max_length=16,
                    ),
                ),
                (
                    "notice_version",
                    models.CharField(default="2026.1-DPDP", max_length=32),
                ),
                ("granted_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("withdrawn_at", models.DateTimeField(blank=True, null=True)),
                ("revocation_reason", models.TextField(blank=True, default="")),
                (
                    "ip_address_masked",
                    models.CharField(default="127.0.0.1", max_length=64),
                ),
                (
                    "user_agent_snippet",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("is_parental_consent", models.BooleanField(default=False)),
                (
                    "guardian_principal_id",
                    models.CharField(blank=True, default="", max_length=64),
                ),
            ],
            options={
                "db_table": "dpdp_consent_records",
                "ordering": ["-granted_at"],
                "indexes": [
                    models.Index(
                        fields=["principal_id", "purpose_id"],
                        name="dpdp_consen_princip_937c9e_idx",
                    ),
                    models.Index(
                        fields=["status"], name="dpdp_consen_status_5db477_idx"
                    ),
                ],
            },
        ),
    ]
